### PR TITLE
fix sizes in matlab

### LINKED ISSUE #14: Matrix return complex double
I'm using MATLAB version. The input variable is double, yet the output variable B is complex double. Is this normal?

### PR DESCRIPTION
**Pull request by agramfort**
closes #14

@NoPenguinsLand can you see if it fixes your problem?

with this code using your data and this code
```
load C

[D, B] = qndiag(C, 'max_iter', 100);
```
it works for me.

### CODE REVIEW

**Comment by NoPenguinsLand** [comment]
Thanks @agramfort, the problem is it does not guarantee it will prevent negative eigenvalue, but then getting an accurate eigenvalue decomposition is not a trivial problem.

A quick and dirty solution I'm using right now is adding line `B = abs(B);` after first declaring and defining the B variable.

**Comment by agramfort** [comment]
Can you share the data to replicate the problem ? I couldn’t with the data you gave

**Comment by NoPenguinsLand** [comment]
Interesting. I'm still using the same data I uploaded in #14, it sounds like we are getting different results from the same data (I'm still getting complex double matrix B). I'm using MATLAB R2020b.

**Comment by agramfort** [comment]
Sorry I only have access to a very old matlab so I don't know how to replicate.

**Comment by NoPenguinsLand** [comment]
No worries, I appreciate that you took the time to look into it. I'll use my quick and dirty solution in the meanwhile. You can close this.

**Pull request merged**
